# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-Win32-ChangeNotify
version:      1.01
version_from: lib/POE/Component/Win32/ChangeNotify.pm
installdirs:  site
requires:
    Carp:                          0
    POE:                           0.31
    Win32::ChangeNotify:           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
