---
abstract: "A POE wrapper around Win32::ChangeNotify.\r"
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Win32-ChangeNotify
no_index:
  directory:
    - inc
requires:
  POE: 0.38
  POE::Filter::Line: 0
  POE::Filter::Reference: 0
  POE::Wheel::Run: 0
  Win32::ChangeNotify: 0
  perl: 5.006
resources:
  homepage: https://github.com/bingos/poe-component-win32-changenotify
  repository: https://github.com/bingos/poe-component-win32-changenotify.git
version: 1.22
