---
abstract: "A POE wrapper around Win32::ChangeNotify.\r"
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: POE-Component-Win32-ChangeNotify
no_index:
  directory:
    - mylib
    - inc
    - t
requires:
  Carp: 0
  POE: 0.38
  POE::Filter::Line: 0
  POE::Filter::Reference: 0
  POE::Wheel::Run: 0
  Win32::ChangeNotify: 0
  strict: 0
  warnings: 0
tests: t/*.t xt/*.t
version: 1.14
